version: '2.1'

services:
  redis:
    image: redis
  express-template:
    image: express-template
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      REDIS_HOST: redis://redis
      SESSION_STORE: redis
    ports:
      - 8000:8000
    depends_on:
      - redis
  

