version: '2.1'

services:
  mongo:
    image: mongo
  express-template:
    image: express-template
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://mongo
      SESSION_STORE: mongo
    ports:
      - 8000:8000
    depends_on:
      - mongo