version: '2.1'

services:
  express-template:
    image: express-template
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000

